matrix_app/urls.py
from django.urls import path
# from rest_framework.routers import DefaultRouter

# from matrix_app.api_views import PostList, PostDetail, UserList, UserDetail, UserPostList, PostViewSet
from . import views

urlpatterns = [
    path('', views.index_view, name='index'),
    path('about/', views.about_view, name='about'),
    path('contact/', views.contact_view, name='contact'),
    path('post/detail/<slug:slug>/', views.post_view, name='detail'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name="logout"),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('register/', views.register_view, name='register'),
    path('post/create/', views.post_create_view, name='post_create'),
    path('post/edit/<int:post_id>/', views.post_edit_view, name='post_edit'),
    path('delete/<int:post_id>/', views.delete_view, name='delete'),
    path('edit/profile/', views.edit_profile_view, name='edit_profile'),
    path('authors/<int:author_id>/', views.author_posts_view, name='author_posts'),
    path('my-posts/', views.my_posts_view, name='my_posts'),
    path('activate/<str:token>/', views.activate_account_view, name='activate_account'),
]



# ''' For routing APIViews '''
# urlpatterns += [
#     path('posts/', PostList.as_view(), name='post_list_1'),
#     path('posts/<int:pk>/', PostDetail.as_view(), name='post_detail_1'),
#     path('users/', UserList.as_view(), name='user_list'),
#     path('users/<int:pk>/', UserDetail.as_view(), name='user_detail'),
#     path('users/<int:pk>/posts', UserPostList.as_view(), name='user_post_list'),
#     # path('users/<int:pk>/posts/<int:pk>/', UserDetail.as_view(), name='user_post_detail'),
#
# ]
#
#
# ''' For Viewset url routing '''
# router = DefaultRouter()
# router.register('posts', PostViewSet, base_name='posts')
#
# urlpatterns += router.urls

matrix_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('matrix_app.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('matrix/', include('matrix_app.api_urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

admin.site.site_title = "Matrix Blog"
admin.site.site_header = "Matrix Blog"
admin.site.index_title = "Admin Panel"

matrix_app/models.py
import random, string
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils import timezone
from django.utils.safestring import mark_safe
from ckeditor_uploader.fields import RichTextUploadingField

User = get_user_model()


def random_token_generator(size=20, chars=string.ascii_letters + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))


class Header(models.Model):
    title = models.CharField(max_length=225)
    sub_title = models.CharField(max_length=300)
    bg_image = models.ImageField(default='home-bg.jpg')

    def __str__(self):
        return '{}'.format(self.title)

    class Meta:
        verbose_name = "Әsas Sәhifә"
        verbose_name_plural = "Әsas Sәhifә"

    def get_bg_image(self):
        if self.bg_image:
            return mark_safe("<img style='width:250px' src='{}' alt=''>".format(self.bg_image.url))


class Menu(models.Model):
    name = models.CharField(max_length=50)
    url = models.CharField(max_length=20, null=True, blank=True)
    order = models.IntegerField(default=0)

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        verbose_name = "Menyu"
        verbose_name_plural = "Menyu"
        ordering = ('order',)


class About(models.Model):
    title = models.CharField(max_length=225)
    sub_title = models.CharField(max_length=300)
    bg_image = models.ImageField(default='about-bg.jpg')
    content = models.TextField()

    def get_bg_image(self):
        if self.bg_image:
            return mark_safe("<img style='width:200px' src='{}' alt=''>".format(self.bg_image.url))
        else:
            return mark_safe("<img  style='width:200px' src='{}' alt=''>".format("about-bg.jpg"))

    class Meta:
        verbose_name = "Haqqımızda"
        verbose_name_plural = "Haqqımızda"


class Contact(models.Model):
    name = models.CharField(max_length=150, verbose_name="Ad")
    email = models.EmailField(verbose_name="Email")
    phone = models.CharField(max_length=10, verbose_name="Telefon")
    message = models.TextField(max_length=250, verbose_name="Mesaj")

    def __str__(self):
        return "{}".format(self.name)

    class Meta:
        verbose_name = 'Əlaqə'
        verbose_name_plural = 'Əlaqə'


class SocialMedia(models.Model):
    name = models.CharField(max_length=100, blank=True)
    icon = models.CharField(max_length=200)
    url = models.URLField(blank=True, null=True)

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        verbose_name = "Sosial şəbəkə"
        verbose_name_plural = "Sosial şəbəkələr"


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    about = models.TextField(null=True, blank=True)
    picture = models.ImageField(default='about-bg.jpg', upload_to='pictures/', null=True, blank=True)

    def __str__(self):
        return '{}'.format(self.user)

    class Meta:
        verbose_name = "Müəllif"
        verbose_name_plural = "Müəlliflər"


class Post(models.Model):
    image = models.ImageField(blank=True, default='default-profile.jpg')
    title = models.CharField(max_length=250, db_index=True)
    sub_title = models.CharField(max_length=250)
    content = RichTextUploadingField()
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    publish_date = models.DateField(default=timezone.now)
    status = models.BooleanField(default=True)
    slug = models.SlugField(unique=True, null=True, blank=True)

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.title_cache = self.title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'slug': self.slug})

    def get_image(self):
        if self.image:
            return mark_safe("<img style='width:200px' src='{}' alt=''>".format(self.image.url))
        else:
            return mark_safe("<img  style='width:200px' src='{}' alt=''>".format(
                "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No"
                "_image_available.svg/1024px-No_image_available.svg.png"))

    def __str__(self):
        return '{}'.format(self.title)

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Postlar"
        ordering = ("-publish_date",)


class Token(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=20, default=random_token_generator)
    activation = models.BooleanField(default=False)

matrix_app/views.py
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMultiAlternatives
from django.shortcuts import render, redirect, get_object_or_404

from matrix_app.models import Header, Menu, Post, About, SocialMedia, Profile, Token
from matrix_app.forms import ContactForm, LoginForm, RegisterForm, PostForm, UserForm, ProfileForm
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.urls import reverse
from django.conf import settings

User = get_user_model()

base_data = {
    'menus': Menu.objects.all(),
    'social': SocialMedia.objects.all(),
}


def index_view(request):
    content = base_data
    content['header'] = Header.objects.first()

    post_list = Post.objects.filter(status=True)

    paginator = Paginator(post_list, 4)
    page = request.GET.get('page', 1)

    if page:
        posts = paginator.get_page(page)
    else:
        posts = paginator.get_page(1)
    max_index = len(paginator.page_range)
    index = int(page) - 1
    start_index = index - 5 if index > 5 else 0
    end_index = index + 5 if index <= max_index else max_index - 1
    content['page_index'] = paginator.page_range[start_index:end_index]

    content['posts'] = posts

    return render(request, 'index.html', content)


def about_view(request):
    content = base_data
    about_model = About.objects.first()
    content['about'] = about_model
    return render(request, 'about.html', content)


def contact_view(request):
    content = base_data
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Mesajınız uğurla göndərildi. Təşəkkür edirik!")
            return redirect('contact')
        else:
            content['form'] = form
            return render(request, 'contact.html', content)
    else:
        content['form'] = form
        return render(request, 'contact.html', content)


def post_view(request, slug):
    content = base_data
    content["post"] = Post.objects.get(slug=slug)
    return render(request, "post.html", content)


def login_view(request):
    content = base_data
    login_form = LoginForm()

    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user and user.is_active:
                if hasattr(user, 'token'):
                    if user.token.activation:
                        login(request, user)
                        return redirect(reverse('dashboard'))
                    else:
                        messages.success(request, 'Hesabınızı aktivləşdirmək üçün mailinizi yoxlayın.')
                        return redirect(reverse('login'))
                login(request, user)
                return redirect(reverse('dashboard'))
            else:
                messages.warning(request, 'Məlumatlarınızı düzgün daxil edin.')
                return redirect(reverse('login'))

    content['login_form'] = login_form
    return render(request, 'login.html', content)


def logout_view(request):
    logout(request)
    return redirect(reverse('login'))


def register_view(request):
    content = base_data
    register_form = RegisterForm()
    if request.method == 'POST':
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            user = register_form.save()
            password = register_form.cleaned_data.get('password')
            user.set_password(password)
            user.save()
            token = Token.objects.create(user=user)
            url = 'http://' + request.get_host() + '/activate/' + token.name
            subject, from_email, to = 'Matrix Activation email', settings.EMAIL_HOST_USER, register_form.cleaned_data.get(
                'email')
            text_content = 'Thank you for registration'
            html_content = "<p><a href='" + url + "'>Please activate your account</a></p>"
            msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
            msg.attach_alternative(html_content, "text/html")
            msg.send()
            messages.success(request, "Aktivasiya mailiniz uğurla göndərildi. Zəhmət olmasa mailinizi yoxlayın.")

            return redirect(reverse('login'))
        else:
            messages.error(request, "Məlumatlarınız keçərli deyil. Zəhmət olmasa yenidən daxil edin.")
            content['register_form'] = register_form
            return render(request, 'register.html', content)
    content['register_form'] = register_form
    return render(request, 'register.html', content)


def activate_account_view(request, token):
    content = base_data
    user_token = Token.objects.filter(name=token)[0]
    if not user_token.activation:
        user_token.activation = True
        user_token.save()
        messages.success(request, 'Hesabınız uğurla aktivləşdirildi.Zəhmət olmasa daxil olun.')
        return redirect(reverse('login'))
    else:
        return redirect(reverse('index'))


@login_required(login_url='login')
def dashboard_view(request):
    content = base_data
    content['posts'] = Post.objects.filter(author__user=request.user)

    post_list = Post.objects.filter(author__user=request.user)

    paginator = Paginator(post_list, 4)
    page = request.GET.get('page', 1)

    if page:
        posts = paginator.get_page(page)
    else:
        posts = paginator.get_page(1)
    max_index = len(paginator.page_range)
    index = int(page) - 1
    start_index = index - 5 if index > 5 else 0
    end_index = index + 5 if index <= max_index else max_index - 1
    content['page_index'] = paginator.page_range[start_index:end_index]

    content['posts'] = posts
    return render(request, 'dashboard.html', content)


@login_required(login_url='login')
def post_create_view(request):
    content = base_data
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            post.author = request.user.profile
            post.save()
            return redirect(reverse('dashboard'))
    content['form'] = form
    content['type'] = 'create'
    return render(request, 'post_form.html', content)


@login_required(login_url='login')
def post_edit_view(request, post_id):
    content = base_data
    the_post = get_object_or_404(Post, id=post_id)
    form = PostForm(instance=the_post)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=the_post)
        if form.is_valid():
            form.save()
            return redirect(reverse('dashboard'))
    content['form'] = form
    content['type'] = 'edit'
    return render(request, 'post_form.html', content)


@login_required(login_url='login')
def delete_view(request, post_id):
    post = Post.objects.get(id=post_id)
    post.delete()
    return redirect(reverse('dashboard'))


@login_required(login_url='login')
def edit_profile_view(request):
    content = base_data
    user_form = UserForm(instance=request.user)
    profile_form = ProfileForm(instance=request.user.profile)

    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            profile = profile_form.save(commit=False)
            profile.user = user_form.save()
            profile.save()
            messages.success(request, 'Məlumatlarınız müvəfəqiyyətlə yeniləndi!')
            return redirect(reverse('edit_profile'))

    content['user_form'] = user_form
    content['profile_form'] = profile_form
    return render(request, 'edit_profile.html', content)


@login_required(login_url='login')
def my_posts_view(request):
    content = base_data
    post_list = Post.objects.filter(author=request.user.profile)

    paginator = Paginator(post_list, 4)
    page = request.GET.get('page', 1)

    if page:
        posts = paginator.get_page(page)
    else:
        posts = paginator.get_page(1)
    max_index = len(paginator.page_range)
    index = int(page) - 1
    start_index = index - 5 if index > 5 else 0
    end_index = index + 5 if index <= max_index else max_index - 1
    content['page_index'] = paginator.page_range[start_index:end_index]

    content['posts'] = posts

    return render(request, 'my_posts.html', content)


def author_posts_view(request, author_id):
    content = base_data
    author = get_object_or_404(Profile, pk=author_id)
    post_list = Post.objects.filter(author_id=author_id)

    paginator = Paginator(post_list, 4)
    page = request.GET.get('page', 1)

    if page:
        posts = paginator.get_page(page)
    else:
        posts = paginator.get_page(1)
    max_index = len(paginator.page_range)
    index = int(page) - 1
    start_index = index - 5 if index > 5 else 0
    end_index = index + 5 if index <= max_index else max_index - 1
    content['page_index'] = paginator.page_range[start_index:end_index]

    content['posts'] = posts
    content['author'] = author

    return render(request, 'author_posts.html', content)

matrix_app/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Page Header -->
    <header class="masthead" style="background-image: url('{{ about.bg_image.url }}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="page-heading">
                        <h2>{{ about.title }}</h2>
                        <span class="subheading">{{ about.sub_title }}</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <p class="text-justify">{{ about.content }}</p>
            </div>
        </div>
    </div>

    <hr>

{% endblock %}

matrix_app/templates/author_posts.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Page Header -->
    <header class="masthead" style="background-image: url({{ author.picture.url }})">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="page-heading">
                        <h2>{{ author.user.get_full_name }}</h2>
                        <span class="subheading text-justify">{{ author.about }}</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
    <div style="text-align:center"><h1>Yayımladığı Xəbərlər</h1></div>
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">

                {% for post in posts %}

                    <div class="post-preview">
                        <a href="{% url 'detail' slug=post.slug %}">
                            <h2 class="post-title">
                                {{ post.title }}
                            </h2>
                            <h3 class="post-subtitle">
                                {{ post.sub_title }}
                            </h3>
                        </a>
                        <p class="post-meta">Posted on {{ post.publish_date }}</p>
                    </div>
                    <hr>
                {% endfor %}

                {% if posts.has_other_pages %}
                    <nav>
                        <ul class="pagination justify-content-end">
                            <li class="page-item">
                                {% if posts.has_previous %}
                                    <a class="btn btn-primary float-right" href="?page={{ posts.previous_page_number }}"
                                       aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                {% endif %}
                            </li>
                            {% for p in page_index %}
                                {% if posts.number == p %}
                                    <li class="page-item"><a class="disabled btn btn-primary float-right"
                                                             href="?page={{ p }}">{{ p }}</a></li>
                                {% else %}
                                    <li class="page-item"><a class="btn btn-primary float-right"
                                                             href="?page={{ p }}">{{ p }}</a></li>
                                {% endif %}
                            {% endfor %}
                            <li class="page-item">
                                {% if posts.has_next %}
                                    <a class="btn btn-primary float-right" href="?page={{ posts.next_page_number }}"
                                       aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                        <span class="sr-only">Next</span>
                                    </a>
                                {% endif %}
                            </li>
                        </ul>
                    </div>
                    </nav>
                {% endif %}
        </div>
    </div>
    </div>
    <hr>
{% endblock %}

matrix_app/templates/edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Page Header -->
    <header class="masthead"
            style="background-image: {% if request.user.profile.picture.url != null %}url({{ request.user.profile.picture.url }})"
                > {% endif %}
            <div class="overlay"></div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-10 mx-auto">
                        <div class="page-heading">
                            <h2>Məlumatlarım</h2>
                            {% if messages %}
                                {% for msg in messages %}
                                    <span class="subheading text-capitalize">{{ msg }}</span>
                                {% endfor %}
                                {% else %}
                                <span class="subheading text-capitalize">Profil məlumatlarını yenilə</span>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in user_form %}
                        <div class="control-group">
                            <div class="form-group floating-label-form-group controls">
                                <label>{{ field.label }}</label>
                                {{ field }}
                                {% if field.errors %}
                                    {% for error in field.errors %}
                                        <p class="help-block text-danger">{{ error }}</p>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}

                    {% for field in profile_form %}
                        <div class="control-group">
                            <div class="form-group floating-label-form-group controls">
                                <label>{{ field.label }}</label>
                                {{ field }}
                                {% if field.errors %}
                                    {% for error in field.errors %}
                                        <p class="help-block text-danger">{{ error }}</p>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                    <br>
                    <div class="form-group float-right">
                        <button type="submit" class="btn btn-primary" id="sendMessageButton">Yadda saxla</button>
                        <a style="color: white;" class="btn btn-danger" id="sendMessageButton">Imtina et</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <hr>
{% endblock %}

{% block ck_script %}

    <script type='text/javascript' src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type='text/javascript' src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker3.min.css">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.standalone.min.css">
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/locales/bootstrap-datepicker.az.min.js"></script>
    <script>
        $("#id_publish_date").datepicker();
    </script>
{% endblock %}

matrix_app/templates/noactivate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>This activation link already is used. <a href="http://127.0.0.1:8000/register/">Please register again</a></h1>
</body>
</html>

matrix_app/templates/post.html
{% extends 'base.html' %}

{% block content %}
    <!-- Page Header -->
    {% load static %}
    <header class="masthead" style="background-image: url('{{ post.image.url }}')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="post-heading text-center">
                        <h2>{{ post.title }}</h2>
                        <h3 class="subheading">{{ post.sub_title }}</h3>
                        <span class="meta">Posted by
                <a href="#">{{ post.author.user.username }}</a>
                on August 24, 2018</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto text-justify">
                    {{ post.content|safe }}
                </div>
            </div>
        </div>
    </article>

    <hr>

{% endblock %}

matrix_app/templates/post_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Page Header -->
    {% if type == 'create' %}
        <header class="masthead" style="background-image: url('{% static 'img/createpost.jpg' %}')">
    {% else %}
        <header class="masthead" style="background-image: url('{% static 'img/editpost.jpg' %}')">
    {% endif %}
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            <div class="page-heading">
                {% if type == 'create' %}
                    <h2>Yeni məqalə yarat</h2>
                {% elif type == 'edit' %}
                    <h2> Məqaləni dəyiş </h2>
                {% endif %}
                <span class="subheading"></span>
            </div>
        </div>
    </div>
</div>
</header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="control-group">
                            <div class="form-group floating-label-form-group controls">
                                <label>{{ field.label }}</label>
                                {% if field.name == 'image' %}
                                    <img class="img-thumbnail" style="width: 200px" src="{{ field.initial.url }}"
                                         alt="">
                                    <input type="file" accept="image/*" name="image" class="form-control">
                                {% elif field.name == 'publish_date' %}
                                    <input name="publish_date" value="{{ field.initial|date:'m/d/Y' }}" required=""
                                           id="id_publish_date"
                                           type="text">
                                {% else %}
                                    <div>
                                        {{ field }}
                                    </div>
                                {% endif %}
                                {% if field.errors %}
                                    {% for error in field.errors %}
                                        <p class="help-block text-danger">{{ error }}</p>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                    <br>
                    <div class="form-group float-right">
                        <button type="submit" class="btn btn-primary" id="sendMessageButton">Yadda saxla</button>
                        <a style="color: white;" class="btn btn-danger" id="sendMessageButton">Imtina et</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <hr>
{% endblock %}

{% block ck_script %}

    <script type='text/javascript' src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type='text/javascript' src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker3.min.css">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.standalone.min.css">
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>
    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/locales/bootstrap-datepicker.az.min.js"></script>
    <script>
        $("#id_publish_date").datepicker();
    </script>
{% endblock %}